# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='counter',
            field=models.IntegerField(default=5),
        ),
    ]
